### ISSUE TITLE
在windows服务器上npm install时，报错

### ISSUE THREAD

**Issue by pengqian089** [leochen-g/wechatBot#33]
日志
``` log
2612 verbose stack Error: command failed
2612 verbose stack     at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
2612 verbose stack     at ChildProcess.emit (events.js:376:20)
2612 verbose stack     at maybeClose (internal/child_process.js:1055:16)
2612 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
2613 verbose pkgid grpc@1.24.10
2614 verbose cwd C:\wechatBot
2615 verbose Windows_NT 10.0.14393
2616 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
2617 verbose node v14.17.0
2618 verbose npm  v7.18.1
2619 error code 1
2620 error path C:\wechatBot\node_modules\grpc
2621 error command failed
2622 error command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
2623 error gyp info it worked if it ends with ok
2623 error gyp info using node-gyp@7.1.2
2623 error gyp info using node@14.17.0 | win32 | x64
2623 error gyp info find Python using Python version 3.9.5 found at "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\python.exe"
2623 error gyp info find VS using VS2019 (16.10.31410.357) found at:
2623 error gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
2623 error gyp info find VS run with --verbose for detailed information
2623 error gyp info spawn C:\Users\Administrator\AppData\Local\Programs\Python\Python39\python.exe
2623 error gyp info spawn args [
2623 error gyp info spawn args   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
2623 error gyp info spawn args   'binding.gyp',
2623 error gyp info spawn args   '-f',
2623 error gyp info spawn args   'msvs',
2623 error gyp info spawn args   '-I',
2623 error gyp info spawn args   'C:\\wechatBot\\node_modules\\grpc\\build\\config.gypi',
2623 error gyp info spawn args   '-I',
2623 error gyp info spawn args   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
2623 error gyp info spawn args   '-I',
2623 error gyp info spawn args   'C:\\Users\\Administrator\\AppData\\Local\\node-gyp\\Cache\\14.17.0\\include\\node\\common.gypi',
2623 error gyp info spawn args   '-Dlibrary=shared_library',
2623 error gyp info spawn args   '-Dvisibility=default',
2623 error gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Administrator\\AppData\\Local\\node-gyp\\Cache\\14.17.0',
2623 error gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
2623 error gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Administrator\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.17.0\\\\<(target_arch)\\\\node.lib',
2623 error gyp info spawn args   '-Dmodule_root_dir=C:\\wechatBot\\node_modules\\grpc',
2623 error gyp info spawn args   '-Dnode_engine=v8',
2623 error gyp info spawn args   '--depth=.',
2623 error gyp info spawn args   '--no-parallel',
2623 error gyp info spawn args   '--generator-output',
2623 error gyp info spawn args   'C:\\wechatBot\\node_modules\\grpc\\build',
2623 error gyp info spawn args   '-Goutput_dir=.'
2623 error gyp info spawn args ]
2623 error gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
2623 error gyp ERR! configure error
2623 error gyp ERR! stack Error: `gyp` failed with exit code: 1
2623 error gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
2623 error gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
2623 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
2623 error gyp ERR! System Windows_NT 10.0.14393
2623 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
2623 error gyp ERR! cwd C:\wechatBot\node_modules\grpc
2623 error gyp ERR! node -v v14.17.0
2623 error gyp ERR! node-gyp -v v7.1.2
2623 error gyp ERR! not ok
2624 verbose exit 1
```
我注意到2623提示 ：Undefined variable module_name in binding.gyp while trying to load binding.gyp
然后我指定module-name值
`node-gyp rebuild --module-name=balabala`
结果还是报错 

``` log
gyp info it worked if it ends with ok
gyp info using node-gyp@8.1.0
gyp info using node@14.17.0 | win32 | x64
gyp info find Python using Python version 3.9.5 found at "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\python.exe"
gyp info find VS using VS2019 (16.10.31410.357) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\Administrator\AppData\Local\Programs\Python\Python39\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\wechatBot\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator\\AppData\\Local\\node-gyp\\Cache\\14.17.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Administrator\\AppData\\Local\\node-gyp\\Cache\\14.17.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Administrator\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.17.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\wechatBot',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\wechatBot\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: binding.gyp not found (cwd: C:\wechatBot) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Administrator\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:353:16)
gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--module-name=dpz"
gyp ERR! cwd C:\wechatBot
gyp ERR! node -v v14.17.0
gyp ERR! node-gyp -v v8.1.0
gyp ERR! not ok
```

有谁遇到过类似的情况吗？请问该怎么解决？

**Comment by leochen-g** [comment]
更换一下node版本为 14.16.0 或者12稳定版再跑一下
