### ISSUE TITLE
Could not find expected browser

### ISSUE THREAD

**Issue by caoping6** [leochen-g/wechatBot#41]
当我运行npm run start时报错：

12:00:58 ERR PuppetWeChatBridge start() exception: Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (848005).
12:00:58 ERR PuppetWeChat initBridge() exception: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (848005).
12:00:58 ERR PuppetWeChat initBridge() this.bridge.stop() rejection: Error: no page
12:00:58 ERR PuppetWeChat start() exception: Error
Error
    at PuppetWeChat.<anonymous> (/Users/caoping/weibo/sourceCode/wechatBot/node_modules/wechaty/dist/src/wechaty.js:273:44)
    at PuppetWeChat.emit (events.js:210:5)
    at PuppetWeChat.EventEmitter.emit (domain.js:476:20)
    at PuppetWeChat.start (/Users/caoping/weibo/sourceCode/wechatBot/node_modules/wechaty-puppet-wechat/dist/src/puppet-wechat.js:106:18)
12:00:58 ERR Wechaty start() exception:
Error
    at PuppetWeChat.<anonymous> (/Users/caoping/weibo/sourceCode/wechatBot/node_modules/wechaty/dist/src/wechaty.js:273:44)
    at PuppetWeChat.emit (events.js:210:5)
    at PuppetWeChat.EventEmitter.emit (domain.js:476:20)
    at PuppetWeChat.start (/Users/caoping/weibo/sourceCode/wechatBot/node_modules/wechaty-puppet-wechat/dist/src/puppet-wechat.js:106:18)

**Comment by caoping6** [comment]
找到了解决办法
https://stackoverflow.com/questions/68051648/could-not-find-expected-browser-chrome-locally
cd ./node_modules/puppeteer
npm run install
