### ISSUE TITLE
项目第二次运行报错

### ISSUE THREAD

**Issue by zgll** [leochen-g/wechatBot#49]
现象：
下载项目，安装依赖，第一次运行，扫码登陆成功。之后我手动停止了运行，第二次执行 node .\index.js

报错：
INFO PuppetManager install(wechaty-puppet-wechat@>=0.28) done
Error: Cannot find module 'gerror'
Require stack:
- D:\wechat-bot\wechatBot-master\wechatBot-master\node_modules\wechaty\node_modules\wechaty-puppet-wechat\dist\cjs\src\puppet-wechat.js
- D:\wechat-bot\wechatBot-master\wechatBot-master\node_modules\wechaty\node_modules\wechaty-puppet-wechat\dist\cjs\src\mod.js
- D:\wechat-bot\wechatBot-master\wechatBot-master\node_modules\wechaty\dist\src\puppet-manager.js
- D:\wechat-bot\wechatBot-master\wechatBot-master\node_modules\wechaty\dist\src\wechaty.js
- D:\wechat-bot\wechatBot-master\wechatBot-master\node_modules\wechaty\dist\src\mod.js
- D:\wechat-bot\wechatBot-master\wechatBot-master\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\wechat-bot\wechatBot-master\wechatBot-master\node_modules\wechaty\node_modules\wechaty-puppet-wechat\dist\cjs\src\puppet-wechat.js:52:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\wechat-bot\wechatBot-master\wechatBot-master\node_modules\wechaty\node_modules\wechaty-puppet-wechat\dist\cjs\src\mod.js:22:28)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at D:\wechat-bot\wechatBot-master\wechatBot-master\node_modules\wechaty\dist\src\puppet-manager.js:122:78
    at async Function.resolveName (D:\wechat-bot\wechatBot-master\wechatBot-master\node_modules\wechaty\dist\src\puppet-manager.js:122:30)
    at async Function.resolve (D:\wechat-bot\wechatBot-master\wechatBot-master\node_modules\wechaty\dist\src\puppet-manager.js:85:30)
    at async Wechaty.initPuppet (D:\wechat-bot\wechatBot-master\wechatBot-master\node_modules\wechaty\dist\src\wechaty.js:247:32)
    at async Wechaty.start (D:\wechat-bot\wechatBot-master\wechatBot-master\node_modules\wechaty\dist\src\wechaty.js:519:13) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\wechat-bot\\wechatBot-master\\wechatBot-master\\node_modules\\wechaty\\node_modules\\wechaty-puppet-wechat\\dist\\cjs\\src\\puppet-wechat.js',
    'D:\\wechat-bot\\wechatBot-master\\wechatBot-master\\node_modules\\wechaty\\node_modules\\wechaty-puppet-wechat\\dist\\cjs\\src\\mod.js',
    'D:\\wechat-bot\\wechatBot-master\\wechatBot-master\\node_modules\\wechaty\\dist\\src\\puppet-manager.js',
    'D:\\wechat-bot\\wechatBot-master\\wechatBot-master\\node_modules\\wechaty\\dist\\src\\wechaty.js',
    'D:\\wechat-bot\\wechatBot-master\\wechatBot-master\\node_modules\\wechaty\\dist\\src\\mod.js',
    'D:\\wechat-bot\\wechatBot-master\\wechatBot-master\\index.js'
  ]
}

**Comment by leochen-g** [comment]
此问题很久之前已经修复。如果还有问题，可以重新打开
