### ISSUE TITLE
启动程序报错，puppet-wechat不可用

### ISSUE THREAD

**Issue by choogoo** [leochen-g/wechatBot#50]
从报错上看都是chromium的问题，除了centos，确定在其他环境下可以正常运行吗？

运行环境一： mac M1

```
luyuchao@MacintoshdeMacBook-Pro-2 wechatBot % npm start

> wechatbot@1.0.1 start
> node index.js

00:06:32 WARN WechatyPuppetMixin start() starting puppet ... timeout
00:06:32 WARN WechatyPuppetMixin start() puppet info: Puppet<PuppetWeChat>(WechatEveryDay)
开始登陆微信
00:06:47 ERR PuppetWeChatBridge start() exception: TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r982053 is guaranteed to work.
00:06:47 ERR PuppetWeChat initBridge() exception: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r982053 is guaranteed to work.
00:06:47 ERR PuppetWeChat initBridge() this.bridge.stop() rejection: Error: no page
```

运行环境二：gitpod

```
gitpod /workspace/wechatBot (master) $ npm start

> wechatbot@1.0.1 start
> node index.js

16:23:03 ERR PuppetWeChatBridge start() exception: Error: Failed to launch the browser process!
/workspace/wechatBot/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

16:23:03 ERR PuppetWeChat initBridge() exception: Failed to launch the browser process!
/workspace/wechatBot/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

16:23:03 ERR PuppetWeChat initBridge() this.bridge.stop() rejection: Error: no page
GError: Failed to launch the browser process!
/workspace/wechatBot/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/workspace/wechatBot/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
    at Interface.<anonymous> (/workspace/wechatBot/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:231:68)
    at Interface.emit (node:events:539:35)
    at Interface.close (node:readline:586:8)
    at Socket.onend (node:readline:277:10)
    at Socket.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 2,
  details: 'Error: Failed to launch the browser process!\n' +
    '/workspace/wechatBot/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory\n' +
    '\n' +
    '\n' +
    'TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n' +
    '\n' +
    '    at onClose (/workspace/wechatBot/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)\n' +
    '    at Interface.<anonymous> (/workspace/wechatBot/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:231:68)\n' +
    '    at Interface.emit (node:events:539:35)\n' +
    '    at Interface.close (node:readline:586:8)\n' +
    '    at Socket.onend (node:readline:277:10)\n' +
    '    at Socket.emit (node:events:539:35)\n' +
    '    at endReadableNT (node:internal/streams/readable:1345:12)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:83:21)'
}
```

**Comment by leochen-g** [comment]
其他平台都是可用的，你可以搜索一下报错内容，看起来是缺少了某些lib库的支持

**Comment by leochen-g** [comment]
拉取最新镜像可以解决 已经切换为wechat4u  无需puppeteer
